#!/bin/bash

rm -Rf .nuget
mkdir .nuget

pushd .nuget

mkdir -p lib/net45
mkdir content
mkdir tools

cp ../bin/Debug/*.dll lib/net45
cp ../Urbas.Example.Bar.nuspec .

nuget pack Urbas.Example.Bar.nuspec

popd
